version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: tracking-postgres
    environment:
      POSTGRES_DB: tracking_db
      POSTGRES_USER: tracking_user
      POSTGRES_PASSWORD: tracking_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tracking_user -d trackingdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  tracking-service:
    build: .
    container_name: tracking-service
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://tracking_user:tracking_password@postgres:5432/trackingdb
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/tracking/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data:
    driver: local
