"""Create tracking_events table

Revision ID: aaae11249768
Revises: 
Create Date: 2025-09-07 17:17:25.037436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaae11249768'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracking_events',
    sa.Column('tracking_event_id', sa.UUID(), nullable=False),
    sa.Column('partner_id', sa.String(length=255), nullable=False),
    sa.Column('campaign_id', sa.String(length=255), nullable=False),
    sa.Column('visitor_id', sa.String(length=255), nullable=False),
    sa.Column('interaction_type', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('destination_url', sa.Text(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('tracking_event_id')
    )
    op.create_index(op.f('ix_tracking_events_campaign_id'), 'tracking_events', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_tracking_events_interaction_type'), 'tracking_events', ['interaction_type'], unique=False)
    op.create_index(op.f('ix_tracking_events_partner_id'), 'tracking_events', ['partner_id'], unique=False)
    op.create_index(op.f('ix_tracking_events_visitor_id'), 'tracking_events', ['visitor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracking_events_visitor_id'), table_name='tracking_events')
    op.drop_index(op.f('ix_tracking_events_partner_id'), table_name='tracking_events')
    op.drop_index(op.f('ix_tracking_events_interaction_type'), table_name='tracking_events')
    op.drop_index(op.f('ix_tracking_events_campaign_id'), table_name='tracking_events')
    op.drop_table('tracking_events')
    # ### end Alembic commands ###
